### ISSUE TITLE
Adding variational approximation and optimization option to speed up computation time

### ISSUE THREAD

**Issue by palmierieugenio** [ropensci/dynamite#76]
I am working with a big dataset and the model is very slow it can take days. For these situations, it may be helpful to allow for variational approximation and optimization options. They appear to be supported both in `rstan` and `cmdstanr`:

[https://mc-stan.org/rstan/reference/stanmodel-method-vb.html](https://mc-stan.org/rstan/reference/stanmodel-method-vb.html)
[https://mc-stan.org/cmdstanr/reference/model-method-variational.html](https://mc-stan.org/cmdstanr/reference/model-method-variational.html)
[https://mc-stan.org/rstan/reference/stanmodel-method-optimizing.html](https://mc-stan.org/rstan/reference/stanmodel-method-optimizing.html)

**Comment by helske** [comment]
Thanks for the suggestion, this could be doable. Perhaps the biggest issue with adding support for these is that the output from some of these are not necessarily compatible with various post processing functions of `dynamite`.

What you can do already is to extract the code and data used for the MCMC by `get_code` and `get_data` functions, which you can then use for optimization or variational inference. The downside of this approach is of course that then you cannot no longer functionality of `dynamite`:
```
d <- get_data(obs(y ~ -1 + z + varying(~ x + lag(y)) + random(~1), family = "gaussian") +
                random_spec() + splines(df = 20),
              data = gaussian_example,
              time = "time",
              group = "id")

model <- rstan::stan_model(model_code = model_code)
fit <- rstan::optimizing(model, data = d)
```

Instead of switching to optimization or variational methods, there's also few potentially useful things you can try: Easiest one is to try within-chain parallelization via `threads_per_chain ` argument. Second option is see if you can modify the generated model code to improve the sampling performance; the current code generation is very general, optimized for a case where you have time-varying covariates and coefficients, so it is possible to improve the performance for some special cases.  After extracting the code with `get_code`, you can modify it (to some extent) and pass it back to `dynamite` call using the `custom_stan_model` argument.

**Comment by palmierieugenio** [comment]
Thanks for the example, I missed the `get_data` functions that makes the use of the other function `get_code` much more user friendly without having to deal with reverse engineering of your code. My suggestion is to add this kind of example in the documentation of `get_code` and in the vignette where you introduce `get_code`, because this function is much more user friendly combined with the function `get_data` and this fact is very easy to miss.

**Comment by helske** [comment]
Thanks, I agree that those functions should be documented better, and they could fit to the vignette describing the `custom_stan_model` argument https://github.com/ropensci/dynamite/issues/77.

**Comment by helske** [comment]
I now added a draft of a vignette on how to use `get_code` and `get_data` functions to create a custom model code which can be used with `rstan::vb` and merged back to `dynamitefit` object. I hope this is helpful.

**Comment by santikka** [comment]
Closing this as completed.
