### ISSUE TITLE
Dynamite fails on dynamic panel data with negative binomial distribution

### ISSUE THREAD

**Issue by davidmosca** [ropensci/dynamite#84]
When I try to fit dynamite to dynamic panel data, I get the errors reported below. The covariates in the data set correspond to marketing channels and the output variable to sales. The original data is confidential but I have created a synthetic data set with the same characteristics, and which produces the same errors.
Is there anything I should change to eliminate those errors?

Code:
```
library('dynamite')
library('tidyverse')

set.seed(1)
n_group <- 50L
n_time <- 20L

df <- data.frame(
  time = rep(seq_len(n_time), each = n_group),
  group = seq_len(n_group)
)

variables <- paste0("var", 1:6)
probs = c(0.90, 0.71, 0.85, 0.95, 0.82, 0.69)

for (i in 1:6){
  is_zero = as.logical(rbinom(n = n_group*n_time, size = 1, prob = probs[i]))
  df[variables[i]] = rpois(n_group*n_time, 4.0)
  df[is_zero, variables[i]] = 0
}

for (i in 1:(n_group*n_time)){
  if (df[i, 'time']==1){
    group = df[i,'group']
    set.seed(group)
    df[i, 'sales'] = rnbinom(1, mu = 1000, size = 1)
  }
  else
    df[i, 'sales'] = round(df[i-n_group, 'sales'] +
                             df[i,'var1'] + df[i-n_group,'var1']/1.7 +
                             5*df[i,'var2'] + df[i-n_group,'var2']/2.1 +
                             sqrt(10*df[i,'var3']) + df[i-n_group,'var3']/3.3 + 
                             df[i,'var4'] + df[i-n_group,'var4']/3.1 + 
                             3*df[i,'var5'] + df[i-n_group,'var5']/4.05 + 
                             2*df[i,'var6'] + df[i-n_group,'var6']/1.2, digits=0)
}

formula <- obs(sales ~ lag(sales) +
                 var1 + lag(var1) +
                 var2 + lag(var2) +
                 var3 + lag(var3) +
                 var4 + lag(var4) +
                 var5 + lag(var5) +
                 var6 + lag(var6) + random(~1), family='negbin')

fit = dynamite(dformula=formula,
               data = df,
               time="time",
               group="group",
               chains=4,
               cores=4)
```

Errors:
```
SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: Rejecting initial value:
Chain 1:   Gradient evaluated at the initial value is not finite.
Chain 1:   Stan can't start sampling from this initial value.
Chain 1: Rejecting initial value:
Chain 1:   Gradient evaluated at the initial value is not finite.
Chain 1:   Stan can't start sampling from this initial value.
etc.
```

Warning messages:
```
1: There were 3781 transitions after warmup that exceeded the maximum treedepth. Increase max_treedepth above 10. See
https://mc-stan.org/misc/warnings.html#maximum-treedepth-exceeded 
2: There were 1 chains where the estimated Bayesian Fraction of Missing Information was low. See
https://mc-stan.org/misc/warnings.html#bfmi-low 
3: Examine the pairs() plot to diagnose sampling problems
 
4: The largest R-hat is 1.26, indicating chains have not mixed.
Running the chains for more iterations may help. See
https://mc-stan.org/misc/warnings.html#r-hat 
5: Bulk Effective Samples Size (ESS) is too low, indicating posterior means and medians may be unreliable.
Running the chains for more iterations may help. See
https://mc-stan.org/misc/warnings.html#bulk-ess 
6: Tail Effective Samples Size (ESS) is too low, indicating posterior variances and tail quantiles may be unreliable.
Running the chains for more iterations may help. See
https://mc-stan.org/misc/warnings.html#tail-ess  
```

**Comment by santikka** [comment]
I get no errors running this on R 4.4.0 and the latest versions of rstan/StanHeaders. I do get roughly the same amount of divergences. This issue does not seem to be related to dynamite specifically, it is Stan that struggles to estimate the model.

Looking at the data, most of the predictors are just zero:
```
> mean(df[, 3:8] == 0)
[1] 0.8186667
```
and seeing how the data is generated, the predictors will not have much influence on the response. I suggest trying a simpler model first.

**Comment by davidmosca** [comment]
Thanks for your answer. I have R 4.4.1, rstan 2.32.6 and StanHeaders 2.32.10 (which are all the latest versions), but I do get the errors mentioned above. What simpler model would you advise to try first? Thanks.

**Comment by santikka** [comment]
I think you can safely ignore these errors if the sampling still succeeds. I would start with a model that only has the most important covariates and without the random effects until you have a model that convergences without issues and then keep building on that. Please see <https://mc-stan.org/misc/warnings.html> for dealing with the runtime warnings of Stan.

**Comment by davidmosca** [comment]
Thanks for the tip. Just to be sure, how do I know whether the sampling succeeds of fails? Any object returned by `dynamite` counts as success?

**Comment by santikka** [comment]
Yes, if the fit object is returned, then the sampling has succeeded. There may be some rare exceptions where this is not the case, but I can't think of one at the moment.

**Comment by helske** [comment]
Getting Stan errors about rejecting initial value is typically nothing to worry about if the model still runs. However, it might be an indication of issues with the data (relative to the model) such as extremely large values of predictors which cause numerical issues.

As @santikka said, technically sampling should have succeeded if the fit object is returned, except in some cases you may get a fit object from Stan with no samples, for example when all chains fail due unexpectedly (this could happen for example if you run out of memory during the sampling).

But, even if the sampling was successful in a technical sense, the sampling might fail from a statistical perspective, as in the above case, due to divergences or other issues of convergence. Here I am not surprised that the model does not converge as the model does not match the way you have generated the data. Your response variables at time points greater than 1 are not a negative binomial but deterministic functions of the first time point and the predictors.

**Comment by davidmosca** [comment]
@helske thanks for your input. This is synthetic data that tries to mimic the real data so not fully representative; however, the real data set throws the same errors. When the data is grouped, how would you choose the distribution? Say that _within_ each group, the response variable is approximately normally distributed, but _across_ groups it follows a negative binomial distribution - which distribution should I use in `dynamite`?

**Comment by helske** [comment]
Because we are modelling the within group dynamics, what matters is how the response for group _i_ at time _t, y_{i,t}_, is distributed when conditioned on the predictors (including, e.g., lagged response). So I'd choose normal distribution in your example. Potential between group differences (after conditioning on predictors) could then be accounted for by including random effects, latent factors, or mixture components (latter are not supported by `dynamite` though).

**Comment by davidmosca** [comment]
I managed to run `dynamite` without errors.
